title: Data Science Computing
author: Andrew Teodorescu
email: amteodo@emory.edu
description: > # this means to ignore newlines until "baseurl:"
  I will write about the projects in QTM 385.

# social links
github_username: amteodo

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
